// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AConfigProvider: typeof import('@arco-design/web-vue')['ConfigProvider']
    ALayoutFooter: typeof import('@arco-design/web-vue')['LayoutFooter']
    Footer: typeof import('./src/components/footer/index.vue')['default']
    Menu: typeof import('./src/components/menu/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
